### ISSUE TITLE
[BUG] Snack isn't working for me

### ISSUE THREAD

**Issue by dBianchii** [gunnartorfis/sonner-native#100]
**Describe the bug**
The snack link provided isn't working, I'm on iOS

**To Reproduce**

1. Go to https://snack.expo.dev/@gunnartorfis/sonner-native
2. Open expo go
3. Cry

**Comment by dBianchii** [comment]
I wanted to try it out before adding it to my project. I think if we fix the snack it can help the package become more popular

**Comment by hichemfantar** [comment]
Crashes on Android, stuck connecting on iOS

**Comment by gunnartorfis** [comment]
@hichemfantar not much I can do about that, as I mentioned Snack failed to install all dependencies.
