### ISSUE TITLE
[BUG] toast.promise error callback

### ISSUE THREAD

**Issue by michaelpomogajko** [gunnartorfis/sonner-native#106]
**Describe the bug**
In original sonner, the error callback of a promise can also take a function with the rejected error as parameter.

**To Reproduce**
```js 
toast.promise(
  new Promise((resolve, reject) => {
    setTimeout(() => {
      reject(new Error('Nah'));
   }, 1000);
  }),
  {
    loading: 'Loading..',
    success: (result: string) => `Resolved:  ${result}`,
    error: (error: Error) => `Rejected: ${error.message}`,
  }
```

**Expected behavior**
Types should allow this, as well as functionality should mimic original sonner

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | latest |
| react-native                 |  latest   |
| react-native-reanimated      |  latest   |
| react-native-gesture-handler |  latest  |

**Comment by bpingris** [comment]
hello! i've opened [a PR](https://github.com/gunnartorfis/sonner-native/pull/99) that should cover that feature

**Comment by gunnartorfis** [comment]
Releasing the fix in an hour or so, closed
