### ISSUE TITLE
`RNSFullWindowOverlay` is displayed full screen, blocking RN inspector

### ISSUE THREAD

**Issue by imWildCat** [gunnartorfis/sonner-native#114]
**Is your feature request related to a problem? Please describe.**

after integrating this lib, I cannot inspect elements

<img width="524" alt="image" src="https://github.com/user-attachments/assets/d97e7a92-a6b1-44bb-9feb-c53578d984e7">

**Describe the solution you'd like**

is that possible to hide it completely if there's no toast?

**Describe alternatives you've considered**

idk, or make it not inspectable?

**Additional context**

**Comment by gunnartorfis** [comment]
@imWildCat could you post your setup? I cannot reproduce this on the example app nor on my own app.

**Comment by dragonfire1119** [comment]
The ToasterOverlayWrapper takes up the full screen, which is impacting the testing process for Maestro.

**Comment by imWildCat** [comment]
sorry for the late response.

I finally figured it out.

instead of the doc sample code
```tsx
import { Toaster } from 'sonner-native';

function App() {
  return (
    <View>
      <NavigationContainer>...</NavigationContainer>
      <Toaster />
    </View>
  );
}
```

I re-ordered the Toast component to move it before the NavigationContainer and it got fixed

<img width="712" alt="image" src="https://github.com/user-attachments/assets/aabb8be5-1829-4b35-8f77-62bcca307860">

**Comment by gunnartorfis** [comment]
@imWildCat could you try out the `0.16.0-beta.0` release? There we're only showing the FullWindowOverlay conditionally if there are any toasts visible.

**Comment by imWildCat** [comment]
thank you @gunnartorfis 

<img width="399" alt="image" src="https://github.com/user-attachments/assets/1a42c205-cd76-45fe-adec-08c01543c738">


it is fixed!

sorry for the delay.

Was debugging another issue for the web and it turns out caused by my workaround
