### ISSUE TITLE
[react-native-gesture-handler] None of the callbacks in the gesture are worklets

### ISSUE THREAD

**Issue by wogno** [gunnartorfis/sonner-native#116]
**Describe the bug**
Always get this warning
Working well, but I have this warning
[react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread.

**To Reproduce**

1. Just install and show toast

**Expected behavior**
Without warning

**Screenshots**

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | 0.14.1  |
| react-native                 | 0.75.3   |
| react-native-reanimated      |3.15.2  |
| react-native-gesture-handler | 2.19.0  |

**Additional context**

**Comment by gunnartorfis** [comment]
Just released 0.14.2, which fixes this. Let me know if it doesn't.

**Comment by wogno** [comment]
I upgrade version to recommended and that work well thanks.
