### ISSUE TITLE
Reanimated Reduced motion

### ISSUE THREAD

**Issue by janroures** [gunnartorfis/sonner-native#128]
Hello, thanks for this amazing lib. I was wondering how to customize the reduced motion setting in reanimated. Animations won't work if we can't set reduceMotion: ReduceMotion.Never

**Comment by janroures** [comment]
would be nice to be able to customize reanimated animation options.

Thank you 🙏

**Comment by gunnartorfis** [comment]
Hey @janroures 
I'm not too deep in reduceMotion - would we have to read the reduce motion on the device settings if we'd want to support this within the lib, and apply it to our animations? 

Would you be open to create a PR?

**Comment by janroures** [comment]
Hi @gunnartorfis thanks for your response,

No, what I mean is that it would be nice to be able to assign the Reduced Motion values that reanimated already has built-in as a global or local prop of the toast, and have it modify the options of the withTiming, withSpring animations, etc. of the toast.

Something like
`toast.success("Hello, world", {
reduceMotion: ReduceMotion.Never
}`
or
`<Toaster theme="dark" toastOptions={{
reduceMotion: ReduceMotion.Never
}}/>`

this is from reanimated: 
<img width="315" alt="Captura de pantalla 2024-10-04 a les 19 22 33" src="https://github.com/user-attachments/assets/0090e2d5-51e4-41fe-bf21-851cb489a623">
<img width="364" alt="Captura de pantalla 2024-10-04 a les 19 29 16" src="https://github.com/user-attachments/assets/87b23584-7f49-4eea-8cd0-1eff371150f6">

Hope I explained myself well!!
Thank you

**Comment by hyoban** [comment]
I think you can already do this with [ReduceMotionConfig](https://github.com/software-mansion/react-native-reanimated/pull/6164)

**Comment by janroures** [comment]
Didn't know about this. Thank you!!!
