### ISSUE TITLE
Customize close button

### ISSUE THREAD

**Issue by ljukas** [gunnartorfis/sonner-native#129]
**Is your feature request related to a problem? Please describe.**
Icon can be replaced to be anything, the same goes for the action and cancel buttons. But the close Icon cannot be customized, you cant even change the color for it without changing the theme of the toast

**Describe the solution you'd like**
Much like the other components Id like it to be replaceable with a custom component

**Describe alternatives you've considered**
Forking this lib and adding this myself, which I will probably do anyway,

**Comment by gunnartorfis** [comment]
I can take a look at this after the weekend. Feel free to create a PR if you want to speed things up 💪
