### ISSUE TITLE
I need forbidPress

### ISSUE THREAD

**Issue by YuGer26** [gunnartorfis/sonner-native#136]
Can you add a control so that the background cannot be clicked during toast?

**Comment by gunnartorfis** [comment]
The background of the toast or the rest of your app?

**Comment by YuGer26** [comment]
For the background of the entire app, I hope that when toast.loading exists, other locations on the page cannot be clicked until toast.dismiss() is executed; I thought of a way and wrote a component nested in sonner-native, adding a method 'forbidPress' to control whether the background can be clicked when toast takes effect. By the way, I optimized the action according to my own preferences. The code is posted below

**Comment by YuGer26** [comment]
`import React, { useState, useEffect } from "react";
import { View, TouchableWithoutFeedback } from "react-native";
import {
  Toaster as OriginalToaster,
  toast as originalToast,
} from "sonner-native";
import { YtoastActions } from "./YtoastActions";

// Create a global state object to manage toast status
const toastState = {
  isToastVisible: false,
  shouldForbidPress: false,
  setIsToastVisible(value) {
    this.isToastVisible = value;
  },
  setShouldForbidPress(value) {
    this.shouldForbidPress = value;
  },
};

// YToaster component for rendering toast and handling full-screen click prevention
export const YToaster = ({ ...props }) => {
  const [, forceUpdate] = useState({});

  // Use useEffect to periodically force update the component, ensuring state changes are reflected in the UI
  useEffect(() => {
    const interval = setInterval(() => forceUpdate({}), 100);
    return () => clearInterval(interval);
  }, []);

  return (
    <>
      {/* Render a full-screen transparent layer to prevent clicks when shouldForbidPress is true */}
      {toastState.shouldForbidPress && (
        <TouchableWithoutFeedback>
          <View
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              zIndex: 9999,
            }}
          />
        </TouchableWithoutFeedback>
      )}
      {/* Render the original Toaster component */}
      <OriginalToaster
        {...props}
        onToastAdd={() => {
          toastState.setIsToastVisible(true);
          forceUpdate({});
        }}
        onToastRemove={() => {
          toastState.setIsToastVisible(false);
          toastState.setShouldForbidPress(false);
          forceUpdate({});
        }}
      />
    </>
  );
};

// Create a custom toast method
const createYtoastMethod =
  (method) =>
  (message, options = {}) => {
    const {
      forbidPress,
      confirmText,
      cancelText,
      onConfirm,
      onCancel,
      ...restOptions
    } = options;

    // Only create custom actions if confirmText or cancelText is provided
    const customAction =
      confirmText || cancelText ? (
        <YtoastActions
          confirmText={confirmText}
          cancelText={cancelText}
          onConfirm={() => {
            if (onConfirm) onConfirm();
            Ytoast.dismiss();
          }}
          onCancel={() => {
            if (onCancel) onCancel();
            Ytoast.dismiss();
          }}
        />
      ) : null;

    // If forbidPress is set, prevent page clicks
    if (forbidPress) {
      toastState.setShouldForbidPress(true);
    }

    // Call the original toast method
    const closeFunction = method(message, {
      ...restOptions,
      action: customAction || restOptions.action,
      onDismiss: (...args) => {
        toastState.setShouldForbidPress(false);
        if (restOptions.onDismiss) {
          restOptions.onDismiss(...args);
        }
      },
      onAutoClose: (...args) => {
        toastState.setShouldForbidPress(false);
        if (restOptions.onAutoClose) {
          restOptions.onAutoClose(...args);
        }
      },
    });

    // Return an object containing the close method
    return {
      ...closeFunction,
      close: (...args) => {
        toastState.setShouldForbidPress(false);
        if (closeFunction && typeof closeFunction === "function") {
          closeFunction(...args);
        } else if (closeFunction && closeFunction.close) {
          closeFunction.close(...args);
        }
        originalToast.dismiss();
      },
    };
  };

// Create a custom Ytoast object containing various toast methods
export const Ytoast = Object.assign(createYtoastMethod(originalToast), {
  success: createYtoastMethod(originalToast.success),
  error: createYtoastMethod(originalToast.error),
  warning: createYtoastMethod(originalToast.warning),
  loading: createYtoastMethod(originalToast.loading),
  promise: createYtoastMethod(originalToast.promise),
  custom: createYtoastMethod(originalToast.custom),
  dismiss: (...args) => {
    toastState.setShouldForbidPress(false);
    return originalToast.dismiss(...args);
  },
  wiggle: (...args) => {
    toastState.setShouldForbidPress(false);
    return originalToast.wiggle(...args);
  },
});

// YToastProvider component for wrapping the application and providing toast functionality
export const YToastProvider = ({ children }) => <>{children}</>;
`

**Comment by YuGer26** [comment]
`import React from "react";
import { View, useColorScheme } from "react-native";
import { Button } from "@fruits-chain/react-native-xiaoshu";

export const YtoastActions = ({
  confirmText,
  cancelText,
  onConfirm,
  onCancel,
}) => {
  const colorScheme = useColorScheme();
  const theme = global.Colors[colorScheme ?? "light"];

  return (
    <View className="flex flex-row w-full justify-end items-center">
      {confirmText && (
        <Button
          text={confirmText}
          onPress={onConfirm}
          onPressDebounceWait={500}
          size="s"
          style={{ backgroundColor: theme.themeButtonBg }}
          textStyle={{
            color: "black",
            fontSize: 12,
            paddingHorizontal: 10,
            fontWeight: 500,
          }}
        />
      )}
      {cancelText && (
        <Button
          text={cancelText}
          onPress={onCancel}
          onPressDebounceWait={500}
          style={{ backgroundColor: theme.reBg }}
          size="s"
          textStyle={{
            color: theme.reText,
            fontSize: 12,
            paddingHorizontal: 10,
            fontWeight: 500,
          }}
        />
      )}
    </View>
  );
};
`

**Comment by gunnartorfis** [comment]
Since <Toaster /> is rendered using `FullWindowOverlay` from `react-native-screens` on iOS, you probably want to use that as well lower in your view hierarchy for your covering view. You might as well experiment with using `Modal` from `react-native`. 

This is definitely out of scope for `sonner-native` and something that should be handled in user-land.

**Comment by YuGer26** [comment]
thanks
