### ISSUE TITLE
Fix types `title` and `variant` in `ExternalToast`

### ISSUE THREAD

**Issue by frozencap** [gunnartorfis/sonner-native#138]
I would like to be able to pass `variant` without having to call a separate function (for wrapping purposes)

```js
toast({title: 'Are you sure?', variant: 'warning', position: 'bottom-center'})
// instead of
toast.warning('Are you sure?', { position: 'bottom-center' })
```

both work but ts is yelling at the first 

looks like this is the culprit 

```ts
type ExternalToast = Omit<
  ToastProps,
  'id' | 'type' | 'title' | 'jsx' | 'promise' | 'variant'
> & {
  id?: string | number;
};
```

**Comment by frozencap** [comment]
sry first one in fact doesn't work, need to pass string as first argument.

**Comment by mrpmohiburrahman** [comment]
( To the maintainer ), If this issue is accepted, I would like to contribute.

**Comment by gunnartorfis** [comment]
Hey @frozencap 

The goal of the library is to offer a complete match of Sonner's API (for web).

As for your wrapper purposes, why can't you create a toast() function of your own that accepts the variant and calls the respective toast function?

**Comment by frozencap** [comment]
cool with that 🫡
thx tor the great work friend
