### ISSUE TITLE
[BUG] Toast Show under Keyboard

### ISSUE THREAD

**Issue by ameer-taghavi** [gunnartorfis/sonner-native#144]
When keyboard is show, Toast will show under keyboard

**To Reproduce**

1. focus on TextInput
2. when show keyboard, show the Toast

**Expected behavior**
show Toast above keyboard

**Screenshots**

https://github.com/user-attachments/assets/2428f272-0259-44e3-aa18-c44d2c934b49

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | 0.15.0   |
| react-native                 |0.71.19   |
| react-native-reanimated      | 3.14.0   |
| react-native-gesture-handler |2.8.0   |

**Comment by ameer-taghavi** [comment]
> As a workaround, you can position the toast on top if the keyboard is open. You can configure position on the toast() call without changing the default position.

`top-center` doesn't work!

**Comment by gunnartorfis** [comment]
@ameer-taghavi could it be that you're rendering the <Toaster /> within the <KeyboardProvider /> from 'react-native-keyboard-controller? If so, try moving the <Toaster /> outside of that:

```ts
<SafeAreaProvider>
  <GestureHandlerRootView>
    <KeyboardProvider>
      <NavigationContainer>
         // QueryClientProvider, etc.
      </NavigationContainer>
    </KeyboardProvider>
    <Toaster
  </GestureHandlerRootView>
</SafeAreaProvider>

**Comment by ameer-taghavi** [comment]
No, I don't use. I fixed temporary by `offset` property

**Comment by gunnartorfis** [comment]
Yeah, it would be out of scope for this library to handle any keyboard interaction. 
I'd strongly suggest using `react-native-keyboard-controller`.

**Comment by sakhnyuk** [comment]
Using `ToasterOverlayWrapper` solved the issue

```
<Sonner
  ToasterOverlayWrapper={({ children }) => (
    <KeyboardStickyView
    >
      {children}
    </KeyboardStickyView>
  )}
/>
```
