### ISSUE TITLE
[BUG] Toast doesn't show after open image picker or any native screens

### ISSUE THREAD

**Issue by ameer-taghavi** [gunnartorfis/sonner-native#145]
**Describe the bug**
I use `react-native-image-picker` to select picture or take picture. after show picker or camera, Toast doesn't show anymore.

**To Reproduce**

1. open picker by `react-native-image-picker` 
2. show Toast

**Screenshots**

https://github.com/user-attachments/assets/7353e68c-9dd8-4e9b-a721-41e688aa5f5a

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | 0.15.0   |
| react-native                 | 0.71.19   |
| react-native-reanimated      | 3.14.0   |
| react-native-gesture-handler | 2.8.0   |

**Comment by gunnartorfis** [comment]
Can you provide a minimum reproducible GitHub repo for me to reproduce this?

**Comment by ameer-taghavi** [comment]
I created a sample app but every thing is ok!
I fixed my problem by update key props to rerender Toast.
```
 <Toaster
     key={updateToastRef}
```
but i don't know why have problem in Main app!
