### ISSUE TITLE
[BUG] (IOS) Removing the last toast will hide it without animation

### ISSUE THREAD

**Issue by ljukas** [gunnartorfis/sonner-native#174]
**Describe the bug**
Since adding the fix that removes the FullWindowDisplay when there are 0 toasts active, the last toast will just disapear instantly instead of animate away such as it does on Android.

**To Reproduce**
Show and toast then hide it.

**Expected behavior**
I expect the last one to animate away aswell

**Screenshots**
IOS
![ios-toast](https://github.com/user-attachments/assets/d5938e33-cf1c-405e-8934-6a47a407fb4b)

ANDROID
![android-toast](https://github.com/user-attachments/assets/3a4974bd-18cd-4250-ae19-5dbbe03e14b3)

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
    "react-native": "0.74.5",
    "react-native-gesture-handler": "2.18.1",
    "react-native-reanimated": "3.12.1",
    "sonner-native": "~0.16.1",

**Additional context**
Id really like to keep the functinoallity with FullWindowDisplay hiding, so that things like maestro works. But I do want it to delay until the animation have completed

**Comment by gunnartorfis** [comment]
@ljukas well spotted. Can you review the PR?

**Comment by ljukas** [comment]
Absolutely, will check

**Comment by gunnartorfis** [comment]
Released in 0.16.2
