### ISSUE TITLE
[BUG] Toast doesn't show on the screen and only shows up for a split second when it's disappearing from the screen.

### ISSUE THREAD

**Issue by AnirudhMemani** [gunnartorfis/sonner-native#175]
**Describe the bug**
I installed this in my frameworkless react-native app with react-native version 0.76.3 and the toast doesn't show on the screen and only shows up for a split second when it's disappearing from the screen.

**To Reproduce**

1. Run npm install sonner-native
2. Run peer dependencies as mentioned in the docs
3. Mount toaster in app.tsx

**Expected behavior**
Must show the toast full time

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | 0.16.1   |
| react-native                 | 0.76.3   |
| react-native-reanimated      | 3.16.3   |
| react-native-gesture-handler | 2.21.2   |
| react-native-svg version  |  15.10.1  |
| react-native-safe-area-context |  4.14.0  |

**Comment by gunnartorfis** [comment]
@AnirudhMemani Could you provide me a screen recording and your code?

**Comment by AnirudhMemani** [comment]
App.tsx:

`javascript
import { GoogleSignin } from "@react-native-google-signin/google-signin";
import React, { useEffect } from "react";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { AppThemeProvider } from "./components/AppThemeProvider";
import AppWrapper from "./components/AppWrapper";
import Loader from "./components/Loader";
import ToastProvider from "./components/ToastProvider";
import RootStackNavigator from "./navigators/RootStackNavigator";
import { persistor, store } from "./redux/store";
import "./styles/global.css";
import "./utils/config";
import { env } from "./utils/config";
import { printLogs } from "./utils/log-utils";

function App(): React.JSX.Element {
    useEffect(() => {
        try {
            GoogleSignin.configure({
                webClientId: env.FIREBASE_WEB_CLIENT_ID,
                scopes: [
                    "email",
                    "openid",
                    "profile",
                    "https://www.googleapis.com/auth/calendar",
                    "https://www.googleapis.com/auth/userinfo.email",
                    "https://www.googleapis.com/auth/userinfo.profile",
                ],
            });
        } catch (error) {
            printLogs("GoogleSignin.configure() | webClientId not found or invalid | Error thrown:", error);
        }
    }, []);

    return (
        <Provider store={store}>
            <PersistGate loading={<Loader alwaysActive />} persistor={persistor}>
                <ToastProvider>
                    <AppThemeProvider>
                        <AppWrapper>
                            <RootStackNavigator />
                        </AppWrapper>
                    </AppThemeProvider>
                </ToastProvider>
            </PersistGate>
        </Provider>
    );
}

export default App;
`

ToastProvider.tsx:

`javascript
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { Toaster } from "sonner-native";

export default function ToastProvider({ children }: { children: React.ReactNode }): React.JSX.Element {
    return (
        <SafeAreaProvider>
            <GestureHandlerRootView>
                <Toaster />
                {children}
            </GestureHandlerRootView>
        </SafeAreaProvider>
    );
}
`

AppWrapper.tsx:

`javascript
import { useColorScheme } from "@/lib/useColorScheme";
import { NavigationContainer } from "@react-navigation/native";
import { SafeAreaView, StatusBar } from "react-native";

export default function AppWrapper({ children }: { children: React.ReactNode }) {
    const { isDarkColorScheme } = useColorScheme();
    return (
        <SafeAreaView className="flex-1 w-full dark:bg-background-dark bg-background">
            <StatusBar
                barStyle={isDarkColorScheme ? "light-content" : "dark-content"}
                className="dark:bg-background-dark bg-background"
            />
            <NavigationContainer>{children}</NavigationContainer>
        </SafeAreaView>
    );
}
`

**Comment by gunnartorfis** [comment]
@AnirudhMemani Where is the <Toaster /> rendered?

**Comment by AnirudhMemani** [comment]
It's rendered inside the Login Page like this:

```
<Button title="Toast" onPress={() => toast.success("This is working???????")} />
```

RootStackNavigator:
``` 
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import SplashScreen from "../screens/SplashScreen";
import LoginScreen from "../screens/login/Login";
import BottomTabNavigator from "./BottomTabNavigator";
import { RootStackParamList } from "./types";

const Stack = createNativeStackNavigator<RootStackParamList>();

function RootStackNavigator(): React.JSX.Element {
    return (
        <Stack.Navigator
            screenOptions={{
                headerShown: false,
            }}
            initialRouteName="Splash"
        >
            <Stack.Screen name="Splash" component={SplashScreen} />
            <Stack.Screen name="Login" component={LoginScreen} />
            <Stack.Screen name="ProtectedRoutes" component={BottomTabNavigator} />
        </Stack.Navigator>
    );
}

export default RootStackNavigator;
```

**Comment by gunnartorfis** [comment]
No, the `<Toaster />`: https://gunnartorfis.github.io/sonner-native/Toaster

**Comment by AnirudhMemani** [comment]
> App.tsx:
> 
> ```js
> import { GoogleSignin } from "@react-native-google-signin/google-signin";
> import React, { useEffect } from "react";
> import { Provider } from "react-redux";
> import { PersistGate } from "redux-persist/integration/react";
> import { AppThemeProvider } from "./components/AppThemeProvider";
> import AppWrapper from "./components/AppWrapper";
> import Loader from "./components/Loader";
> import ToastProvider from "./components/ToastProvider";
> import RootStackNavigator from "./navigators/RootStackNavigator";
> import { persistor, store } from "./redux/store";
> import "./styles/global.css";
> import "./utils/config";
> import { env } from "./utils/config";
> import { printLogs } from "./utils/log-utils";
> 
> function App(): React.JSX.Element {
>     useEffect(() => {
>         try {
>             GoogleSignin.configure({
>                 webClientId: env.FIREBASE_WEB_CLIENT_ID,
>                 scopes: [
>                     "email",
>                     "openid",
>                     "profile",
>                     "https://www.googleapis.com/auth/calendar",
>                     "https://www.googleapis.com/auth/userinfo.email",
>                     "https://www.googleapis.com/auth/userinfo.profile",
>                 ],
>             });
>         } catch (error) {
>             printLogs("GoogleSignin.configure() | webClientId not found or invalid | Error thrown:", error);
>         }
>     }, []);
> 
>     return (
>         <Provider store={store}>
>             <PersistGate loading={<Loader alwaysActive />} persistor={persistor}>
>                 <ToastProvider>
>                     <AppThemeProvider>
>                         <AppWrapper>
>                             <RootStackNavigator />
>                         </AppWrapper>
>                     </AppThemeProvider>
>                 </ToastProvider>
>             </PersistGate>
>         </Provider>
>     );
> }
> 
> export default App;
> ```
> 
> ToastProvider.tsx:
> 
> ```js
> import { GestureHandlerRootView } from "react-native-gesture-handler";
> import { SafeAreaProvider } from "react-native-safe-area-context";
> import { Toaster } from "sonner-native";
> 
> export default function ToastProvider({ children }: { children: React.ReactNode }): React.JSX.Element {
>     return (
>         <SafeAreaProvider>
>             <GestureHandlerRootView>
>                 <Toaster />
>                 {children}
>             </GestureHandlerRootView>
>         </SafeAreaProvider>
>     );
> }
> ```
> 
> AppWrapper.tsx:
> 
> ```js
> import { useColorScheme } from "@/lib/useColorScheme";
> import { NavigationContainer } from "@react-navigation/native";
> import { SafeAreaView, StatusBar } from "react-native";
> 
> export default function AppWrapper({ children }: { children: React.ReactNode }) {
>     const { isDarkColorScheme } = useColorScheme();
>     return (
>         <SafeAreaView className="flex-1 w-full dark:bg-background-dark bg-background">
>             <StatusBar
>                 barStyle={isDarkColorScheme ? "light-content" : "dark-content"}
>                 className="dark:bg-background-dark bg-background"
>             />
>             <NavigationContainer>{children}</NavigationContainer>
>         </SafeAreaView>
>     );
> }
> ```

The ToastProvider here. Inside App.tsx

**Comment by gunnartorfis** [comment]
<img width="625" alt="Screenshot 2024-12-09 at 22 05 28" src="https://github.com/user-attachments/assets/3387cf84-c4fa-460e-8f23-6ea62cfa1491">
The original comment was missing the <Toaster />

Have you tried moving the Toaster to be rendered after the NavigationContainer?

**Comment by AnirudhMemani** [comment]
Okay, moving it after the NavigationContainer worked.
