### ISSUE TITLE
[BUG] When the toast is displayed at the bottom, the tab navigation cannot be clicked.

### ISSUE THREAD

**Issue by hyoban** [gunnartorfis/sonner-native#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment info**

| Library                         | Version |
| ------------------------------- | ------- |
| react-native-reanimated-toasts            | x.x.x   |
| react-native                    | x.x.x   |
| react-native-reanimated         | x.x.x   |
| react-native-gesture-handler    | x.x.x   |

**Additional context**

**Comment by gunnartorfis** [comment]
@hyoban can you review the PR? #35
