### ISSUE TITLE
[BUG] None of the callbacks in the gesture are worklets - warning by gesture handler

### ISSUE THREAD

**Issue by fobos531** [gunnartorfis/sonner-native#44]
Thank you for the awesome library!

**Describe the bug**

It is basically the same issue as this: https://github.com/dohooo/react-native-reanimated-carousel/issues/654

**To Reproduce**

1. Render a simple toast.

**Expected behavior**

The warning should not appear.

**Screenshots**

![CleanShot 2024-09-08 at 19 09 04@2x](https://github.com/user-attachments/assets/7f42eee3-1b5b-4a0a-8b68-6e46f508a8d2)

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | 0.7.0   |
| react-native                 | 0.75.2   |
| react-native-reanimated      | 3.15.1   |
| react-native-gesture-handler | 2.19.0   |

**Additional context**

Based on the discussion in the linked issue, and this link: https://docs.swmansion.com/react-native-gesture-handler/docs/#automatic-workletization-of-gesture-callbacks

this should already work based on how you defined the gesture, so I'm not sure why the callbacks are not being automatically workletized. You may need to use a workaround similar to this one: https://github.com/dohooo/react-native-reanimated-carousel/pull/577

**Comment by gunnartorfis** [comment]
Hmmm. I haven't seen this warning myself. 

Could you try to downgrade react-native-gesture-handler and see if the warning goes away? I'm personally running 2.16.2.

**Comment by hyoban** [comment]
I have the same problem with 2.19.0, 2.16.2 works fine for me.

**Comment by matinzd** [comment]
Hey!

You need to define 'worklet' explicitly in order for them to run on UI thread. That is a valid warning and it shows that those callbacks are not being run on UI thread.  

Here is the fix:

https://github.com/gunnartorfis/sonner-native/pull/47
