### ISSUE TITLE
Consider using react-native-z-view (for Android)

### ISSUE THREAD

**Issue by gunnartorfis** [gunnartorfis/sonner-native#50]
I haven't tested Android very thoroughly, but it might run into some issues with being on top of everything in some cases. 
We should experiment with [using react-native-z-view](https://github.com/intergalacticspacehighway/react-native-z-view).

The only drawback is that this would require an extra native dependency and since react-native-z-view isn't widely used, it would mean a native update in order to use sonner-native. If we'd somehow make it optional, like checking if react-native-z-view is present in the consumer app, that'd be the best solution.

**Comment by fobos531** [comment]
Also worth considering whether this library supports the new architecture.

**Comment by hirbod** [comment]
@fobos531 it does not support the new architecture yet, but Nishan will add support for it soon.

**Comment by Elue-dev** [comment]
> I haven't tested Android very thoroughly, but it might run into some issues with being on top of everything in some cases. 
> We should experiment with [using react-native-z-view](https://github.com/intergalacticspacehighway/react-native-z-view).
> 
> The only drawback is that this would require an extra native dependency and since react-native-z-view isn't widely used, it would mean a native update in order to use sonner-native. If we'd somehow make it optional, like checking if react-native-z-view is present in the consumer app, that'd be the best solution. 
> 
> 

I can confirm that issues occur on android, check out the recording below

https://github.com/user-attachments/assets/4c1d4d55-3ce8-44f4-96f0-8f3bf73a9943

how do I work around this, with the react native z view  suggested?

**Comment by gunnartorfis** [comment]
@Elue-dev I've never used `react-native-z-view` myself but here's a Twitter discussion you might want to check out: https://twitter.com/hirbod_dev/status/1833059372622086398
