### ISSUE TITLE
Manually copy the SVG icons from lucide-react-native?

### ISSUE THREAD

**Issue by gunnartorfis** [gunnartorfis/sonner-native#51]
- Would remove dependency to lucide
- Would minimize the bundle size

<img width="665" alt="Screenshot 2024-09-09 at 10 31 08" src="https://github.com/user-attachments/assets/d7dc3ca4-3ff8-452d-9774-07b287df2f17">

**Comment by hyoban** [comment]
This is quite important because there is currently no good support for tree shaking.
