### ISSUE TITLE
Add Customisation of Themes (dark mode & light mode)

### ISSUE THREAD

**Issue by Elue-dev** [gunnartorfis/sonner-native#68]
**Is your feature request related to a problem? Please describe.**
Unable to manually set whether the toast uses dark mode or ligt mode

**Describe the solution you'd like**
I would like to be able to configure whether the toast uses dark mode or light mode. Can be added as part of the Toaster component, or when calling the toast components

**Comment by gunnartorfis** [comment]
Thanks for the report, it'll be fixed with #70
