### ISSUE TITLE
lucide-react-native & react-native-svg

### ISSUE THREAD

**Issue by gunnartorfis** [gunnartorfis/sonner-native#8]
Ideally, we'd want to have no unnecessary dependencies like react-native-svg. Using react-native-vector-icons is also bloating the lib so we wouldn't be better off with that. 

The only other option that I can think of is to ditch icons entirely in the lib and have them passed down as props, but I don't like that option much either. 

Any suggestions?

**Comment by gunnartorfis** [comment]
@hyoban what is your thought on this?

**Comment by hyoban** [comment]
react-native-svg is fine, as almost every project using svg icon uses it. For `lucide-react-native`, maybe we copy the icons we use to this package.

**Comment by gunnartorfis** [comment]
True. Let's keep this as is for now.
