### ISSUE TITLE
Support multi Direction in swipe to dismiss

### ISSUE THREAD

**Issue by ameer-taghavi** [gunnartorfis/sonner-native#86]
Please add multi direction in to dismiss 
for example 
`swipToDismissDirections={['up', 'down', 'left', 'right']}`

** down direction is useful for bottom toast

**Comment by gunnartorfis** [comment]
I'll create a separate issue for dismissing by default down for bottom toasts.

**Comment by gunnartorfis** [comment]
Closing this issue as I don't think this is a good UX. #93 will address the most important thing here which is bottom swiping for bottom toasts.
