### ISSUE TITLE
Docs: Add a "web support" section

### ISSUE THREAD

**Issue by gunnartorfis** [gunnartorfis/sonner-native#88]
Been receiving a few questions if this has web support. 

Would want to point out to the following setup:

```ts
// sonner.ts
export * from 'sonner-native';
```

```ts
// sonner.web.ts
export * from 'sonner';
```

And mention that the APIs match so it will work on native & web platforms.

**Comment by Code-Victor** [comment]
Dope! 
Awesome work.

**Comment by GustavoBonfimS** [comment]
When I try to add Sonner to my project and use it on the web, as you described, I encounter the following error: 'Unable to resolve "sonner" from "src/lib/Sonner/index.web.ts".'

Do you know how to solve this issue? Thank you for your great work!

**Comment by gunnartorfis** [comment]
Could you show me more code for context?

**Comment by GustavoBonfimS** [comment]
I created a basic reproduction example here:
https://github.com/GustavoBonfimS/sonner-native-web-test

In my tests, the only way to make Sonner work is by editing node_modules/sonner/package.json to include a main field. This way, I can run the web app with Sonner working.

**Comment by gunnartorfis** [comment]
@GustavoBonfimS thanks. Is platform specific file endings working in the project in general? If you just create some Text component that says "Hello" on native and "Hello Web" on .web.tsx?

**Comment by GustavoBonfimS** [comment]
Yes, I have platform-specific file extensions in other files in my app, and they worked fine before adding Sonner.

Could Sonner be breaking because of the Package Exports support in React Native? Are you able to use Sonner by following the setup in the documentation?

**Comment by gunnartorfis** [comment]
I'm using this setup in my production apps. There's one slight difference:

```ts
// toast.ts
export { toast, Toaster } from "sonner-native";
```

```ts
// toast.web.ts
export { toast, Toaster } from "sonner";
```

Could you try that instead of the * export?

**Comment by GustavoBonfimS** [comment]
This is causing errors as well 😢

What version of React Native are you using in your app? Could you try creating a new expo project and installing the library?

**Comment by gunnartorfis** [comment]
Seems like an open issue in Sonner: https://github.com/emilkowalski/sonner/pull/473
