### ISSUE TITLE
[Feature] add onPress props

### ISSUE THREAD

**Issue by ameer-taghavi** [gunnartorfis/sonner-native#96]
Please add OnPress on whole Toast to run an action without button 🙏🏻

**Comment by gunnartorfis** [comment]
This is not something Sonner for web supports, so this won't get a high priority. 
I encourage you to contribute with a PR.

**Comment by ameer-taghavi** [comment]
I don't have permission to push

**Comment by gunnartorfis** [comment]
You have to fork the repo and make a PR from yours.
