### ISSUE TITLE
[BUG] `onClick` of the action button does not trigger on Android.

### ISSUE THREAD

**Issue by SohelIslamImran** [gunnartorfis/sonner-native#98]
**Describe the bug**
The `onClick` function we pass in the action object in the toast does not trigger on Android but works on iOS. The action button is not clickable on Android I think.

**To Reproduce**

```ts
toast.info("Update available", {
      description:
        "An update is available with many improvements and bug fixes, instantly update for the best experience.",
      duration: Infinity,
      action: {
        label: "Update",
        onClick: async () => {
          console.log("Clicked update button");
        },
      },
    });
  ```

1. Click on the update button

**Expected behavior**
The provided action onClick function should trigger on Android

**Screenshots**

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | ^0.13.0  |
| react-native                 | 0.74.5   |
| react-native-reanimated      | ~3.10.1  |
| react-native-gesture-handler | ~2.16.2   |

**Additional context**
Maybe sometime double clicking very quickly trigger it

**Comment by SohelIslamImran** [comment]
Also, using custom Pressable is still not trigger, is not pressable

**Comment by gunnartorfis** [comment]
Two things I found out:
- If the Infinity duration is removed, it works. Setting it to a very high value still works. 
- If the enabled check to the ToastSwipeHandler is removed, it works.

**Comment by SohelIslamImran** [comment]
@gunnartorfis In my case, it is still not working if the Infinity duration is removed.. I need to double click very quickly, then it works
